#
# docker-compose.yml
# MopidyForNAS
#
# Created by CbS Ghost on 03/14/2021.
# Copyright (c) 2021 CbS Ghost. Released under MIT license.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
version: "3"

services:
  mopidy-server:
    container_name: "mopidy-server"
    image: "ivdata/mopidy:latest"
    user: "0:0" #FIXME: QTS does not configure audio properly for normal usage except you're using their HD Station. Use UID=0 is not a good way to fix it.
    devices:
      - "/dev/snd"
    networks:
      default:
        ipv4_address: "172.20.0.100"
    ports:
      - "6680:6680/tcp" # Mopidy web client port
      #- "6600:6600"    # MPD port
    environment:
      - "APT_PACKAGES=gstreamer1.0-alsa"
      - "NODE_ENV=production"
      #- "PIP_PACKAGES=-U Mopidy Mopidy-Iris Mopidy-Spotify Mopidy-YouTube Mopidy-YTMusic"
      - "PIP_PACKAGES=-U Mopidy Mopidy-Iris Mopidy-Spotify https://github.com/natumbri/mopidy-youtube/archive/fix/issue-134.zip Mopidy-YTMusic" # Temp fix for YouTube
      #- "UPDATE=true"
    volumes:
      - "mopidy-data:/mopidy/core:rw"
      - "mopidy-media:/mopidy/media:rw"
      - "./mopidy.conf:/mopidy/mopidy.conf:ro"
    restart: "always"
    #privileged: "true"
    #ipc: "host"
    deploy:
      resources:
        limits:
          cpus: "1.50"
          memory: "640M"

networks:
  default:
    ipam:
      config:
        - subnet: "172.20.0.0/24"
          ip_range: "172.20.0.0/24"
          gateway: "172.20.0.1"

volumes:
  mopidy-data:
    external: "true"
  mopidy-media:
    external: "true"
